name: faltso.org
email: info&#64;faltso.gr
timezone: Greece/Athens

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
      start_line: 1
      
keep_files: []
page_excerpts: true

defaults:
        - scope:
            path: ""
            type: "pages"
          values:
            layout: "default"
        - scope:
            path: ""
            type: "posts"
          values:
            layout: "post"
            excerpt_separator: <!--more-->
        - scope:
            path: ""
            type: "people"
          values:
            layout: "person"
            nohero: true
        - scope:
            path: "assets/css"
          values:
            layout: "styles"
        - scope:
            path: "/assets/img"
          values:
            image: true
        
          
plugins:
        - jekyll-postcss


collections:
    people:
        output: true
    projects:
        output: true
        order: 
            - rock-band/index.md
            - music-play/index.md
            - group-singing/index.md
            - computer-music/index.md

